2025-03-24 16:31:15 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]
2025-03-24 16:31:15 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]
2025-03-24 16:31:15 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:28]
2025-03-24 16:31:15 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:118]
2025-03-24 16:31:15 - __main__ - INFO - Load ID 927771 was generated for this data load - [bfs_publishing_schedule.py:82]
2025-03-24 16:31:15 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 927771" - [bfs_publishing_schedule.py:90]
2025-03-24 16:31:15 - __main__ - INFO - Generated load ID 927771 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:95]
2025-03-24 16:31:15 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:136]
2025-03-24 16:31:15 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:146]
2025-03-24 16:43:55 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]
2025-03-24 16:43:55 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]
2025-03-24 16:43:55 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:28]
2025-03-24 16:43:55 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:118]
2025-03-24 16:43:55 - __main__ - INFO - Load ID 980225 was generated for this data load - [bfs_publishing_schedule.py:82]
2025-03-24 16:43:55 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 980225" - [bfs_publishing_schedule.py:90]
2025-03-24 16:43:55 - __main__ - INFO - Generated load ID 980225 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:95]
2025-03-24 16:43:55 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:136]
2025-03-24 16:43:55 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:146]
2025-03-24 16:44:04 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]
2025-03-24 16:44:04 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]
2025-03-24 16:44:04 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:28]
2025-03-24 16:44:04 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:118]
2025-03-24 16:44:04 - __main__ - INFO - Load ID 101000 was generated for this data load - [bfs_publishing_schedule.py:82]
2025-03-24 16:44:04 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 101000" - [bfs_publishing_schedule.py:90]
2025-03-24 16:44:04 - __main__ - INFO - Generated load ID 101000 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:95]
2025-03-24 16:44:04 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:136]
2025-03-24 16:44:04 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:146]

==================================================
New Run: 2025-03-24 16:53:36.564455 | Run ID: c07f0d84
==================================================
f'[RUN-{run_id}] 2025-03-24 16:53:36 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:162]'
f'[RUN-{run_id}] 2025-03-24 16:53:36 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]'
f'[RUN-{run_id}] 2025-03-24 16:53:36 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]'
f'[RUN-{run_id}] 2025-03-24 16:53:36 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:41]'
f'[RUN-{run_id}] 2025-03-24 16:53:36 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:131]'
f'[RUN-{run_id}] 2025-03-24 16:53:36 - __main__ - INFO - Load ID 154892 was generated for this data load - [bfs_publishing_schedule.py:95]'
f'[RUN-{run_id}] 2025-03-24 16:53:36 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 154892" - [bfs_publishing_schedule.py:103]'
f'[RUN-{run_id}] 2025-03-24 16:53:36 - __main__ - INFO - Generated load ID 154892 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:108]'

==================================================
New Run: 2025-03-24 16:54:57.725289 | Run ID: c4b4b256
==================================================
f'[RUN-{run_id}] 2025-03-24 16:54:57 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:161]'
f'[RUN-{run_id}] 2025-03-24 16:54:57 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:40]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:130]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Load ID 360835 was generated for this data load - [bfs_publishing_schedule.py:94]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 360835" - [bfs_publishing_schedule.py:102]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Generated load ID 360835 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:107]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:148]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:158]'
f'[RUN-{run_id}] 2025-03-24 16:54:58 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:163]'

==================================================
New Run: 2025-03-24 16:56:25.220002 | Run ID: 7ce44cd3
==================================================
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:161]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:40]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:130]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Load ID 582872 was generated for this data load - [bfs_publishing_schedule.py:94]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 582872" - [bfs_publishing_schedule.py:102]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Generated load ID 582872 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:107]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:148]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:158]'
f'[RUN-{run_id}] 2025-03-24 16:56:25 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:163]'

============================================================
New Run: 2025-03-24 16:57:55.803734 | Run ID: 9806a385
============================================================
f'[RUN-{run_id}] 2025-03-24 16:57:55 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:161]'
f'[RUN-{run_id}] 2025-03-24 16:57:55 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]'
f'[RUN-{run_id}] 2025-03-24 16:57:55 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]'
f'[RUN-{run_id}] 2025-03-24 16:57:55 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:40]'
f'[RUN-{run_id}] 2025-03-24 16:57:55 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:130]'
f'[RUN-{run_id}] 2025-03-24 16:57:55 - __main__ - INFO - Load ID 350356 was generated for this data load - [bfs_publishing_schedule.py:94]'
f'[RUN-{run_id}] 2025-03-24 16:57:56 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 350356" - [bfs_publishing_schedule.py:102]'
f'[RUN-{run_id}] 2025-03-24 16:57:56 - __main__ - INFO - Generated load ID 350356 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:107]'
f'[RUN-{run_id}] 2025-03-24 16:57:56 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:148]'
f'[RUN-{run_id}] 2025-03-24 16:57:56 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:158]'
f'[RUN-{run_id}] 2025-03-24 16:57:56 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:163]'

============================================================
New Run: 2025-03-24 16:58:21.956822 | Run ID: 878d40c6
============================================================
f'[RUN-{run_id}] 2025-03-24 16:58:21 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:161]'
f'[RUN-{run_id}] 2025-03-24 16:58:21 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:40]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:130]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Load ID 744243 was generated for this data load - [bfs_publishing_schedule.py:94]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 744243" - [bfs_publishing_schedule.py:102]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Generated load ID 744243 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:107]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:148]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:158]'
f'[RUN-{run_id}] 2025-03-24 16:58:22 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:163]'

============================================================
New Run: 2025-03-24 17:04:52.643136 | Run ID: c31baa9c
============================================================

============================================================
New Run: 2025-03-24 17:06:00.841468 | Run ID: 7ab19f88
============================================================
[RUN-(run_id)s] 2025-03-24 17:06:00 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:168]
[RUN-(run_id)s] 2025-03-24 17:06:00 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]
[RUN-(run_id)s] 2025-03-24 17:06:01 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:47]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:137]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Load ID 943278 was generated for this data load - [bfs_publishing_schedule.py:101]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 943278" - [bfs_publishing_schedule.py:109]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Generated load ID 943278 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:114]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:155]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:165]
[RUN-(run_id)s] 2025-03-24 17:06:01 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:170]

============================================================
New Run: 2025-03-24 17:12:07.263917 | Run ID: 73ede140
============================================================
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:161]
[RUN-(run_id)s] 2025-03-24 17:12:07 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]
[RUN-(run_id)s] 2025-03-24 17:12:07 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:40]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:130]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Load ID 417819 was generated for this data load - [bfs_publishing_schedule.py:94]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 417819" - [bfs_publishing_schedule.py:102]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Generated load ID 417819 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:107]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:148]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:158]
[RUN-(run_id)s] 2025-03-24 17:12:07 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:163]

============================================================
New Run: 2025-03-24 17:14:05.917438 | Run ID: e30815df
============================================================
[RUN-e30815df] 2025-03-24 17:14:05 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:161]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:40]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:130]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Load ID 887740 was generated for this data load - [bfs_publishing_schedule.py:94]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 887740" - [bfs_publishing_schedule.py:102]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Generated load ID 887740 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:107]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:148]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:158]
[RUN-e30815df] 2025-03-24 17:14:06 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:163]

============================================================
New Run: 2025-03-24 17:15:27.638005 | Run ID: 8c45227f
============================================================
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:161]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:40]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:130]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Load ID 486634 was generated for this data load - [bfs_publishing_schedule.py:94]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 486634" - [bfs_publishing_schedule.py:102]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Generated load ID 486634 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:107]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:148]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:158]
[RUN-8c45227f] 2025-03-24 17:15:27 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:163]

============================================================
New Run: 2025-03-24 17:26:15.533847 | Run ID: 78f1fff0
============================================================
[RUN-78f1fff0] 2025-03-24 17:26:15 - __main__ - INFO - Started execution of main block - [bfs_publishing_schedule.py:176]
[RUN-78f1fff0] 2025-03-24 17:26:15 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): dam-api.bfs.admin.ch:443 - [connectionpool.py:1049]
[RUN-78f1fff0] 2025-03-24 17:26:16 - urllib3.connectionpool - DEBUG - https://dam-api.bfs.admin.ch:443 "GET /hub/api/dam/agenda HTTP/1.1" 200 56014 - [connectionpool.py:544]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Successfully fetched source data from BFS API - [bfs_publishing_schedule.py:55]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Trying to connect to the database:
Username -> "kmitiy"
Password -> [REDACTED]
Host -> "localhost"
Port -> "5432"
DB Name -> "bfs" - [bfs_publishing_schedule.py:145]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Load ID 898772 was generated for this data load - [bfs_publishing_schedule.py:109]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Executing query: "SELECT COUNT(*) FROM steering.bfs_publications WHERE load_id = 898772" - [bfs_publishing_schedule.py:117]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Generated load ID 898772 was not found in column LOAD_ID of target table BFS_PUBLICATIONS in schema STEERING, so it can be used - [bfs_publishing_schedule.py:122]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Successfully inserted 20 records into table BFS_PUBLICATIONS of schema STEERING - [bfs_publishing_schedule.py:163]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Connection to BFS is closed - [bfs_publishing_schedule.py:173]
[RUN-78f1fff0] 2025-03-24 17:26:17 - __main__ - INFO - Finished execution of main block - [bfs_publishing_schedule.py:178]
